# Adapted from M. Brett's .yaml file for nipy:
# https://github.com/nipy/nipy/blob/master/.travis.yml
#
# We pretend to be erlang because we need can't use the python support in
# travis-ci; it uses virtualenvs, they do not have numpy, scipy, matplotlib,
# and it is impractical to build them

language: erlang
env:
    # Enable python 2 and python 3 builds. Python3.2 available in Ubuntu 12.04.
    - PYTHON=python EASY_INSTALL=easy_install PIP=pip
    - PYTHON=python3 EASY_INSTALL=easy_install3 PIP=pip-3.2
install:
    - sudo apt-get update -qq
    - sudo apt-get install $PYTHON-dev $PYTHON-numpy $PYTHON-scipy
    - sudo apt-get install $PYTHON-setuptools $PYTHON-nose
    - sudo apt-get install $PYTHON-nibabel $PYTHON-nitime $PYTHON-pandas
    - sudo $PIP install scikit-learn
    - COVERAGE=--with-coverage
    - MNE_FORCE_SERIAL=1
    - MNE_SKIP_SAMPLE_DATASET_TESTS=1
    - if [ "${COVERAGE}" == "--with-coverage" ]; then sudo pip install coverage; fi
    - if [ "${COVERAGE}" == "--with-coverage" ]; then sudo pip install coveralls; fi
    - python setup.py build
    - python setup.py install
    - myscripts='browse_raw bti2fiff surf2bem'
    - for script in $myscripts; do mne $script --help >/dev/null; done;
    - SRC_DIR=$(pwd)
    - cd ~
    - MNE_DIR=$(python -c 'import mne;print mne.__path__[0]')
    - ln -s ${SRC_DIR}/mne/fiff/tests/data ${MNE_DIR}/fiff/tests/data
    - ln -s ${SRC_DIR}/mne/fiff/bti/tests/data ${MNE_DIR}/fiff/bti/tests/data
    - ln -s ${SRC_DIR}/mne/fiff/edf/tests/data ${MNE_DIR}/fiff/edf/tests/data
    - ln -s ${SRC_DIR}/mne/fiff/kit/tests/data ${MNE_DIR}/fiff/kit/tests/data
    - ln -s ${SRC_DIR}/mne/fiff/brainvision/tests/data ${MNE_DIR}/fiff/brainvision/tests/data
script:
    - cd ${MNE_DIR}/../
    - TEST="nosetests -v --exe mne"
    - TEST_COVER="nosetests -v --exe --with-coverage --cover-package=mne
      --cover-html --cover-html-dir=coverage mne"
    - if [ "${COVERAGE}" == "--with-coverage" ]; then ${TEST};
      else ${TEST_COVER}; fi
after_success:
    - if [ "${COVERAGE}" == "--with-coverage" ]; then coveralls; fi
