name: 🛠️ Feature request

# See the json schema to help you create / update this form
# https://json.schemastore.org/github-issue-forms.json

description: Suggest an idea for this project

labels: ["ENH"]

body:

  - type: markdown
    attributes:
      value: |
        Please use the [MNE-Python forum](https://mne.discourse.group/) to ask (and answer)
        concrete technical questions or about usage of MNE-BIDS.
        Use this form if you want to suggest new features.

  - type: textarea
    attributes:
      label: Describe the new feature or enhancement
      description: |
        Please provide a clear and concise description of what you want to add or change.

  - type: textarea
    attributes:
      label: Describe your proposed implementation
      description: |
        Describe how you think the feature or improvement should be implemented (e.g.,
        as a new method on an existing class? as new capability added to an existing
        method?) If you're not sure, please delete this section and the next section.*

  - type: textarea
    attributes:
      label: Describe possible alternatives
      description: |
        If you've suggested an implementation above, list here any alternative
        implementations you can think of, and brief comments explaining why the chosen
        implementation is better.

  - type: textarea
    attributes:
      label: Additional context
      description: |
        Add any other context or screenshots about the feature request here.
